-- ============================================================================
-- BleuLearn Sovereign Curriculum -- Database Schema
-- AvaBleu House HQ | 2026
--
-- TARGET: Postgres (designed for Vercel Postgres / Neon, but is plain
-- standard Postgres -- it will run on any Postgres 13+ instance).
--
-- HOW TO RUN THIS:
--   Option A (recommended, zero manual steps): deploy this codebase with
--   MIGRATE_SECRET set in your Vercel environment, then make one request:
--     curl -X POST https://yourdomain.vercel.app/api/migrate \
--       -H "Authorization: Bearer YOUR_MIGRATE_SECRET"
--   /api/migrate.js runs exactly this file. It is idempotent (every
--   statement is CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS),
--   so it is always safe to re-run.
--
--   Option B (manual): open the Vercel Postgres dashboard's Query tab
--   (or `psql $POSTGRES_URL`) and paste this file's contents directly.
--
-- DESIGN NOTE: points_ledger, attendance, and benchmark_scores are
-- append-style and never updated in place by the API layer. This matches
-- the existing BleuLearn philosophy documented elsewhere in this curriculum:
-- "points are never subtracted, only added" and every assessment event is
-- a documented record, not an overwritten cell. The schema enforces that
-- philosophy structurally, not just by convention.
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
  id            SERIAL PRIMARY KEY,
  email         TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('scholar','teacher','family','admin','case_manager')),
  full_name     TEXT NOT NULL,
  grade_level   TEXT,                 -- only meaningful for role = 'scholar'
  house         TEXT CHECK (house IN ('Harriet','Mansa','Esteban','Pauli') OR house IS NULL),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Links a family account to one or more scholar accounts (handles siblings).
CREATE TABLE IF NOT EXISTS family_links (
  family_user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  scholar_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (family_user_id, scholar_user_id)
);

-- Every point event, ever. Never updated or deleted by application code.
-- A scholar's total is SUM(points) WHERE scholar_user_id = ?, computed on read.
CREATE TABLE IF NOT EXISTS points_ledger (
  id              SERIAL PRIMARY KEY,
  scholar_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  points          INTEGER NOT NULL,
  reason          TEXT NOT NULL,
  strand          TEXT,
  awarded_by      INTEGER REFERENCES users(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_points_scholar ON points_ledger(scholar_user_id);

-- One row per scholar per day. Re-marking the same day updates that one row
-- (see ON CONFLICT in api/attendance.js) -- this is the one table where an
-- update is correct, because a day's attendance is a single fact, not a log.
CREATE TABLE IF NOT EXISTS attendance (
  id              SERIAL PRIMARY KEY,
  scholar_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date            DATE NOT NULL,
  status          TEXT NOT NULL CHECK (status IN ('present','excused_absent','unexcused_absent','tardy')),
  recorded_by     INTEGER REFERENCES users(id),
  notes           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (scholar_user_id, date)
);
CREATE INDEX IF NOT EXISTS idx_attendance_scholar ON attendance(scholar_user_id);

-- One row per scholar per strand per quarter. This is the official transcript
-- record per the Grading and Transcript Policy (Part IV.1 of the Master Doc):
-- level 1=Beginning, 2=Approaching, 3=Proficient, 4=Advanced.
CREATE TABLE IF NOT EXISTS benchmark_scores (
  id              SERIAL PRIMARY KEY,
  scholar_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  strand          TEXT NOT NULL,
  quarter         TEXT NOT NULL,        -- e.g. '2026-Q1'
  level           INTEGER NOT NULL CHECK (level BETWEEN 1 AND 4),
  notes           TEXT,
  recorded_by     INTEGER REFERENCES users(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (scholar_user_id, strand, quarter)
);
CREATE INDEX IF NOT EXISTS idx_benchmark_scholar ON benchmark_scores(scholar_user_id);

-- Every lesson plan generated by /api/generate-lesson-plan.js is saved here
-- when the requester is logged in, plus any manually authored ones a teacher
-- chooses to save through the same endpoint.
CREATE TABLE IF NOT EXISTS lesson_plans (
  id          SERIAL PRIMARY KEY,
  created_by  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  strand      TEXT NOT NULL,
  grade_level TEXT NOT NULL,
  topic       TEXT NOT NULL,
  content     TEXT NOT NULL,
  source      TEXT NOT NULL DEFAULT 'ai_generated' CHECK (source IN ('ai_generated','manual')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_lesson_plans_creator ON lesson_plans(created_by);

-- Capstone progress, one row per scholar that is updated as the scholar
-- advances through the documented Grade 9-12 timeline (see the Capstone
-- Handbook). This one is intentionally mutable -- it tracks current state,
-- not a log of every change.
CREATE TABLE IF NOT EXISTS capstone_records (
  id                SERIAL PRIMARY KEY,
  scholar_user_id   INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  stage             TEXT NOT NULL DEFAULT 'Introduction'
                      CHECK (stage IN ('Introduction','Practice','Proposal','Research_Phase1',
                                        'Research_Phase2','First_Draft','Revision','Final','Showcase','Archived')),
  title             TEXT,
  research_question TEXT,
  mentor_id         INTEGER REFERENCES users(id),
  notes             TEXT,
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- LMS CORE EXTENSION -- added to actually earn the name "LMS"
-- AvaBleu House HQ | BleuLearn Sovereign Curriculum | 2026
--
-- Everything above this line was the original foundation (auth, points,
-- attendance, benchmarks, saved lesson plans). Everything below brings the
-- platform to genuine Moodle-core parity for: courses/sections/enrollment,
-- assignments + submissions + grading, a real weighted gradebook, a quiz
-- engine with a question bank and auto-grading, discussion forums, activity
-- completion tracking, notifications, and an audit log.
--
-- Deliberately NOT attempted here, and said plainly rather than silently
-- skipped: SCORM/H5P content packages, a plugin/theme system, full
-- course backup-and-restore, a granular capability/permission matrix
-- beyond role+role_in_course, badges and competency framework UI, and a
-- calendar UI (due dates ARE queryable via assignments.due_at and
-- quizzes.available_until, so calendar data exists -- there is just no
-- dedicated calendar table or UI yet).
-- ============================================================================

-- A course is a real teachable unit now, not just a string label on a strand.
-- "strand" still records which of the 25 BleuLearn strands this course
-- belongs to, so existing curriculum content stays connected to it.
CREATE TABLE IF NOT EXISTS courses (
  id          SERIAL PRIMARY KEY,
  strand      TEXT NOT NULL,
  title       TEXT NOT NULL,
  grade_level TEXT NOT NULL,
  description TEXT,
  created_by  INTEGER REFERENCES users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Ordered units within a course (Moodle calls these "topics" or "sections").
CREATE TABLE IF NOT EXISTS course_sections (
  id        SERIAL PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  title     TEXT NOT NULL,
  position  INTEGER NOT NULL DEFAULT 0,
  summary   TEXT
);
CREATE INDEX IF NOT EXISTS idx_sections_course ON course_sections(course_id);

-- Who is in which course, and in what capacity. A teacher can be enrolled
-- as 'teacher' in their own course; a scholar as 'student'.
CREATE TABLE IF NOT EXISTS enrollments (
  id            SERIAL PRIMARY KEY,
  course_id     INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_in_course TEXT NOT NULL CHECK (role_in_course IN ('student','teacher','ta')),
  enrolled_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (course_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_enroll_course ON enrollments(course_id);
CREATE INDEX IF NOT EXISTS idx_enroll_user ON enrollments(user_id);

CREATE TABLE IF NOT EXISTS assignments (
  id              SERIAL PRIMARY KEY,
  course_id       INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  section_id      INTEGER REFERENCES course_sections(id) ON DELETE SET NULL,
  title           TEXT NOT NULL,
  instructions    TEXT,
  due_at          TIMESTAMPTZ,
  points_possible NUMERIC NOT NULL DEFAULT 100,
  created_by      INTEGER REFERENCES users(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_assignments_course ON assignments(course_id);

-- Text-based submissions only. File upload submissions are explicitly NOT
-- built here -- that needs Vercel Blob storage (a separate provisioning
-- step, like Postgres was), and is named in DEVELOPER_SETUP.md as the next
-- piece rather than faked with a column that has nothing real behind it.
CREATE TABLE IF NOT EXISTS submissions (
  id               SERIAL PRIMARY KEY,
  assignment_id    INTEGER NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
  scholar_user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  submission_text  TEXT,
  submitted_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  grade            NUMERIC,
  feedback         TEXT,
  graded_by        INTEGER REFERENCES users(id),
  graded_at        TIMESTAMPTZ,
  status           TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('draft','submitted','graded','returned')),
  UNIQUE (assignment_id, scholar_user_id)
);
CREATE INDEX IF NOT EXISTS idx_submissions_assignment ON submissions(assignment_id);
CREATE INDEX IF NOT EXISTS idx_submissions_scholar ON submissions(scholar_user_id);

-- Weighted gradebook categories (e.g. "Tests 40%, Homework 30%, Participation 30%").
CREATE TABLE IF NOT EXISTS grade_categories (
  id        SERIAL PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  name      TEXT NOT NULL,
  weight    NUMERIC NOT NULL DEFAULT 0 CHECK (weight >= 0 AND weight <= 100)
);

-- Every gradeable thing in a course rolls up into grade_items, whether it
-- originated as an assignment, a quiz, or a manually-entered grade. This
-- is what makes a real weighted gradebook possible instead of scattered
-- unrelated scores.
CREATE TABLE IF NOT EXISTS grade_items (
  id              SERIAL PRIMARY KEY,
  course_id       INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  category_id     INTEGER REFERENCES grade_categories(id) ON DELETE SET NULL,
  item_type       TEXT NOT NULL CHECK (item_type IN ('assignment','quiz','manual')),
  item_ref_id     INTEGER,        -- assignments.id or quizzes.id when item_type matches; null for manual
  title           TEXT NOT NULL,
  points_possible NUMERIC NOT NULL DEFAULT 100
);
CREATE INDEX IF NOT EXISTS idx_grade_items_course ON grade_items(course_id);

CREATE TABLE IF NOT EXISTS grades (
  id               SERIAL PRIMARY KEY,
  grade_item_id    INTEGER NOT NULL REFERENCES grade_items(id) ON DELETE CASCADE,
  scholar_user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  points_earned    NUMERIC,
  feedback         TEXT,
  graded_by        INTEGER REFERENCES users(id),
  graded_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (grade_item_id, scholar_user_id)
);
CREATE INDEX IF NOT EXISTS idx_grades_scholar ON grades(scholar_user_id);

-- Quiz engine: two question types to start (multiple_choice auto-grades;
-- short_answer auto-grades on an exact case-insensitive match and is also
-- flagged for teacher review, since free-text grading is genuinely hard
-- to do honestly without a much larger NLP scope than belongs here).
CREATE TABLE IF NOT EXISTS quizzes (
  id                  SERIAL PRIMARY KEY,
  course_id           INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  title               TEXT NOT NULL,
  time_limit_minutes  INTEGER,
  available_from      TIMESTAMPTZ,
  available_until     TIMESTAMPTZ,
  created_by          INTEGER REFERENCES users(id),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quiz_questions (
  id             SERIAL PRIMARY KEY,
  quiz_id        INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  question_text  TEXT NOT NULL,
  question_type  TEXT NOT NULL CHECK (question_type IN ('multiple_choice','short_answer')),
  options        JSONB,            -- multiple_choice only: [{"id":"a","text":"..."}, ...]
  correct_answer TEXT NOT NULL,    -- multiple_choice: option id. short_answer: expected text.
  points         NUMERIC NOT NULL DEFAULT 1,
  position       INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_questions_quiz ON quiz_questions(quiz_id);

CREATE TABLE IF NOT EXISTS quiz_attempts (
  id              SERIAL PRIMARY KEY,
  quiz_id         INTEGER NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  scholar_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  submitted_at    TIMESTAMPTZ,
  score           NUMERIC,
  max_score       NUMERIC,
  status          TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress','submitted'))
);
CREATE INDEX IF NOT EXISTS idx_attempts_scholar ON quiz_attempts(scholar_user_id);

CREATE TABLE IF NOT EXISTS quiz_responses (
  id              SERIAL PRIMARY KEY,
  attempt_id      INTEGER NOT NULL REFERENCES quiz_attempts(id) ON DELETE CASCADE,
  question_id     INTEGER NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,
  response_text   TEXT,
  is_correct      BOOLEAN,
  points_awarded  NUMERIC,
  UNIQUE (attempt_id, question_id)
);

-- Discussion forums. This maps directly onto the curriculum's own
-- documented Discourse Ladder and Harkness pedagogy -- a forum thread is
-- a natural home for asynchronous Structured Academic Controversy or
-- pre-Harkness preparation between class sessions.
CREATE TABLE IF NOT EXISTS forums (
  id          SERIAL PRIMARY KEY,
  course_id   INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  description TEXT,
  created_by  INTEGER REFERENCES users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS forum_posts (
  id              SERIAL PRIMARY KEY,
  forum_id        INTEGER NOT NULL REFERENCES forums(id) ON DELETE CASCADE,
  parent_post_id  INTEGER REFERENCES forum_posts(id) ON DELETE CASCADE,
  author_id       INTEGER NOT NULL REFERENCES users(id),
  body            TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_posts_forum ON forum_posts(forum_id);

-- Activity completion tracking (Moodle's completion checkmarks).
CREATE TABLE IF NOT EXISTS activity_completions (
  id            SERIAL PRIMARY KEY,
  user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL CHECK (activity_type IN ('assignment','quiz','forum','section')),
  activity_id   INTEGER NOT NULL,
  completed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, activity_type, activity_id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id         SERIAL PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type       TEXT NOT NULL,
  message    TEXT NOT NULL,
  link       TEXT,
  is_read    BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, is_read);

-- Audit trail -- Moodle's "Logs" report. Every consequential write in the
-- API layer calls lib/activityLog.js's record() function, which inserts
-- here. This is append-only by design, same reasoning as points_ledger.
CREATE TABLE IF NOT EXISTS activity_log (
  id         SERIAL PRIMARY KEY,
  user_id    INTEGER REFERENCES users(id),
  action     TEXT NOT NULL,
  context    TEXT,
  details    JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_activity_log_user ON activity_log(user_id);

-- ============================================================================
-- SECURITY HARDENING EXTENSION
-- AvaBleu House HQ | BleuLearn Sovereign Curriculum | 2026
--
-- Added after auditing this codebase against real, current Moodle CVEs
-- (CVE-2025-26529 admin takeover via stored XSS; CVE-2025-49517 unauthenticated
-- SQLi; CVE-2025-49516 SSRF; CVE-2026-7274/7275 plugin-related SQLi/RCE) and
-- finding analogous, real problems in this codebase. See SECURITY_AUDIT.md
-- for the full finding-by-finding writeup.
-- ============================================================================

-- Closes the signup privilege-escalation hole: public signup can no longer
-- create a 'teacher' or 'admin' account without a valid, unused, unexpired
-- invite code issued by an existing admin (or the one-time bootstrap path
-- for the very first admin -- see api/auth/signup.js).
CREATE TABLE IF NOT EXISTS invite_codes (
  id          SERIAL PRIMARY KEY,
  code        TEXT UNIQUE NOT NULL,
  role        TEXT NOT NULL CHECK (role IN ('teacher','admin','case_manager')),
  created_by  INTEGER REFERENCES users(id),
  used_by     INTEGER REFERENCES users(id),
  used_at     TIMESTAMPTZ,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Closes the brute-force/credential-stuffing hole on login. Every login
-- attempt (success or failure) is recorded; login.js checks this table
-- before allowing a new attempt and locks out after 5 failures in 15 minutes.
CREATE TABLE IF NOT EXISTS login_attempts (
  id          SERIAL PRIMARY KEY,
  email       TEXT NOT NULL,
  succeeded   BOOLEAN NOT NULL,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_login_attempts_email ON login_attempts(email, attempted_at);

-- Badges (a real Schoology/competitor strength this platform lacked).
CREATE TABLE IF NOT EXISTS badges (
  id          SERIAL PRIMARY KEY,
  title       TEXT NOT NULL,
  description TEXT,
  icon        TEXT,
  created_by  INTEGER REFERENCES users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_badges (
  id         SERIAL PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  badge_id   INTEGER NOT NULL REFERENCES badges(id) ON DELETE CASCADE,
  awarded_by INTEGER REFERENCES users(id),
  awarded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, badge_id)
);

-- ============================================================================
-- ACCOMMODATION AND ENROLLMENT-LIFECYCLE EXTENSION
-- AvaBleu House HQ | BleuLearn Sovereign Curriculum | 2026
--
-- Added after testing two real scenarios end to end: a transfer student and
-- a scholar with an IEP. Both exposed genuine gaps. The Master Curriculum
-- document already contained a "Formal Accommodation Policy" in prose --
-- this is the first time it is actually represented in the running system.
-- ============================================================================

-- Documented accommodation plans (IEP or 504). Deliberately NOT a flag on
-- the users table -- a plan has its own lifecycle (start date, review
-- date, status) independent of the user account itself, and a scholar
-- could in principle have more than one historical plan over time.
CREATE TABLE IF NOT EXISTS accommodation_plans (
  id                       SERIAL PRIMARY KEY,
  scholar_user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  plan_type                TEXT NOT NULL CHECK (plan_type IN ('IEP','504')),
  extended_time_multiplier NUMERIC NOT NULL DEFAULT 1.0 CHECK (extended_time_multiplier >= 1.0),
  notes                    TEXT,
  status                   TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
  created_by               INTEGER REFERENCES users(id),
  start_date               DATE NOT NULL DEFAULT CURRENT_DATE,
  review_date              DATE,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_accommodation_scholar ON accommodation_plans(scholar_user_id, status);

-- Enrollment lifecycle: previously an enrollment row could never represent
-- a student who left. Adding status and withdrawn_at instead of deleting
-- the row, because deleting would destroy the scholar's grade/attendance
-- history along with it (foreign keys cascade) -- a real transfer record
-- needs the history to survive even after the student is gone.
ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','withdrawn','transferred_out'));
ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS withdrawn_at TIMESTAMPTZ;
ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS withdrawal_notes TEXT;

-- Captured at attempt-start time (not recomputed at submit time), so it
-- reflects whatever accommodation was active when the scholar began --
-- changing their plan mid-attempt should not retroactively change an
-- attempt already in progress.
ALTER TABLE quiz_attempts ADD COLUMN IF NOT EXISTS effective_time_limit_minutes INTEGER;

-- ============================================================================
-- INTAKE AND DIFFERENTIATION ASSESSMENT EXTENSION
-- AvaBleu House HQ | BleuLearn Sovereign Curriculum | 2026
--
-- The prior accommodation_plans table only ever captured ONE dimension
-- (a time multiplier) -- it never represented an actual assessment of HOW
-- to teach a scholar. This extension adds the real assessment workflows:
-- a transfer-student diagnostic and curriculum-gap review, an IEP
-- instructional assessment, and a Gifted identification-plus-ongoing-
-- calibration process. A new track_assignments table is the operative
-- "what does a teacher (or the AI lesson generator) actually use right
-- now" record -- the other tables are the documented evidence behind it.
-- ============================================================================

-- One intake record per transferring scholar. The "review of curriculum
-- from the other school" lives in curriculum_gap_findings below, linked
-- to this record -- this table is just the intake context.
CREATE TABLE IF NOT EXISTS transfer_records (
  id                         SERIAL PRIMARY KEY,
  scholar_user_id            INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  prior_school_name          TEXT,
  prior_school_curriculum_notes TEXT, -- what the prior school used/covered, in the registrar's or family's own words
  transfer_date              DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by                 INTEGER REFERENCES users(id),
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_transfer_scholar ON transfer_records(scholar_user_id);

-- Per-strand gap analysis: what did the prior school actually cover for
-- this strand, what does BleuLearn expect at this grade level, and what
-- documented gap exists between the two. This is the direct answer to
-- "review of curriculum from the other school to see what they lack."
CREATE TABLE IF NOT EXISTS curriculum_gap_findings (
  id                      SERIAL PRIMARY KEY,
  transfer_record_id      INTEGER NOT NULL REFERENCES transfer_records(id) ON DELETE CASCADE,
  strand                  TEXT NOT NULL,
  prior_school_coverage   TEXT,  -- documented: what topics/skills the prior school's curriculum covered
  bleulearn_expected_level TEXT, -- documented: what BleuLearn's scope and sequence expects at this grade
  documented_gap          TEXT NOT NULL, -- the specific, named gap (never left vague -- matches the curriculum's "documented" standard)
  severity                TEXT NOT NULL DEFAULT 'minor' CHECK (severity IN ('none','minor','significant')),
  recommended_action      TEXT, -- e.g. "Bridge Track for 6 weeks on fraction operations specifically"
  reviewed_by             INTEGER REFERENCES users(id),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gap_findings_transfer ON curriculum_gap_findings(transfer_record_id);

-- The actual administered diagnostic. Reused across three real purposes
-- so the same documented-evidence structure applies to all of them:
-- a transfer student's placement diagnostic, a Gifted Program
-- identification assessment, or a general mid-year placement check.
CREATE TABLE IF NOT EXISTS placement_assessments (
  id                  SERIAL PRIMARY KEY,
  scholar_user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  transfer_record_id  INTEGER REFERENCES transfer_records(id) ON DELETE SET NULL, -- set only when purpose = transfer_diagnostic
  strand              TEXT NOT NULL,
  purpose             TEXT NOT NULL CHECK (purpose IN ('transfer_diagnostic','gifted_identification','general_placement')),
  score_level         INTEGER NOT NULL CHECK (score_level BETWEEN 1 AND 4), -- same 1-4 scale as benchmark_scores, for consistency
  documented_evidence TEXT NOT NULL, -- what was observed -- never just a number with no documentation
  recommended_track   TEXT NOT NULL CHECK (recommended_track IN ('bridge','grade_level','gifted')),
  administered_by     INTEGER REFERENCES users(id),
  administered_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_placement_scholar ON placement_assessments(scholar_user_id, strand);

-- The instructional-design findings behind an accommodation plan --
-- distinct from accommodation_plans' operational time-multiplier field.
-- This is what actually tells a teacher HOW to teach this scholar, not
-- just how much extra time to give them.
CREATE TABLE IF NOT EXISTS iep_evaluations (
  id                          SERIAL PRIMARY KEY,
  accommodation_plan_id       INTEGER NOT NULL REFERENCES accommodation_plans(id) ON DELETE CASCADE,
  area_assessed               TEXT NOT NULL, -- e.g. 'Reading Comprehension', 'Executive Function', 'Written Expression'
  present_level_of_performance TEXT NOT NULL, -- documented PLAAFP-style description of where the scholar currently is
  documented_strengths        TEXT,
  documented_needs             TEXT,
  recommended_strategies       TEXT NOT NULL, -- e.g. "chunk instructions into 3 steps max; visual schedule; check for understanding every 10 min"
  assessed_by                  INTEGER REFERENCES users(id),
  assessed_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_iep_eval_plan ON iep_evaluations(accommodation_plan_id);

-- Ongoing Gifted Program calibration -- the "not too easy, not
-- overwhelming" check. Distinct from the one-time identification
-- (placement_assessments with purpose='gifted_identification'); this is
-- meant to be administered periodically (the Quarterly Benchmark cycle
-- already documented elsewhere in this curriculum is the natural fit).
CREATE TABLE IF NOT EXISTS gifted_calibration_checkins (
  id                  SERIAL PRIMARY KEY,
  scholar_user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  strand              TEXT NOT NULL,
  quarter             TEXT NOT NULL, -- e.g. '2026-Q1', matching benchmark_scores' convention
  challenge_rating    TEXT NOT NULL CHECK (challenge_rating IN ('too_easy','appropriate','too_challenging')),
  evidence_notes      TEXT NOT NULL, -- documented: what specifically showed this (boredom/disengagement, frustration, etc.)
  recommended_action  TEXT NOT NULL CHECK (recommended_action IN ('extend_challenge','maintain','reduce_challenge')),
  recorded_by         INTEGER REFERENCES users(id),
  recorded_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (scholar_user_id, strand, quarter)
);
CREATE INDEX IF NOT EXISTS idx_gifted_checkin_scholar ON gifted_calibration_checkins(scholar_user_id);

-- THE operative record: what track is this scholar actually on, per
-- strand, right now. Assessments above are the documented evidence;
-- this is the single place a teacher or the AI lesson generator reads to
-- know how to differentiate for a specific scholar today. One active
-- row per scholar per strand -- history is preserved by not deleting,
-- only superseding (old row's is_current flips to false).
CREATE TABLE IF NOT EXISTS track_assignments (
  id              SERIAL PRIMARY KEY,
  scholar_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  strand          TEXT NOT NULL,
  track           TEXT NOT NULL CHECK (track IN ('bridge','grade_level','gifted')),
  reason          TEXT NOT NULL, -- documented justification, e.g. "placement_assessments #14" or "gifted_calibration_checkins #7"
  is_current      BOOLEAN NOT NULL DEFAULT true,
  assigned_by     INTEGER REFERENCES users(id),
  assigned_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_track_current ON track_assignments(scholar_user_id, strand, is_current);

-- ============================================================================
-- AI-ASSISTED, BIAS-AWARE REVIEW WORKFLOW + REMAINING GAP CLOSURE
-- AvaBleu House HQ | BleuLearn Sovereign Curriculum | 2026
--
-- Closes three previously-documented open items (case manager role,
-- structured scope-and-sequence reference, overdue-review tracking) and
-- adds a mandatory AI-assisted second opinion on every placement,
-- IEP, and Gifted decision -- with teacher/admin approval ALWAYS required
-- before the AI's read becomes operative. The AI never decides alone.
-- ============================================================================

-- BEST-EFFORT SAFETY NET ONLY -- the real fix is in the CREATE TABLE
-- statement above, which now includes case_manager from the start, so a
-- fresh database (this platform has not been provisioned in production
-- yet) needs nothing further. This block exists only in case migrate.js
-- was already run once against a real database before this fix shipped.
--
-- VERIFIED LIMITATION, NOT ASSUMED: testing this exact DROP/ADD pattern
-- against an in-memory Postgres test engine showed the guessed name
-- (the documented Postgres default, table_column_check) did NOT match
-- what that engine actually used -- meaning a guessed name cannot be
-- trusted blindly even when it follows documented convention. Real
-- Postgres may or may not match the guess. This statement is left in as
-- a no-cost attempt (IF EXISTS makes it safe to fail silently), but is
-- NOT relied upon as the actual fix.
--
-- IF YOU HAVE ALREADY RUN MIGRATE.JS AGAINST A REAL DATABASE before this
-- update: run this in psql to find the real constraint name, then drop
-- and recreate it yourself with the correct name:
--   SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint
--   WHERE conrelid = 'users'::regclass AND contype = 'c';
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check_v2 CHECK (role IN ('scholar','teacher','family','admin','case_manager'));

-- Structured scope-and-sequence reference, so "what does BleuLearn expect
-- at this grade" in a curriculum gap finding is a selection from documented
-- content, not free text relying on one teacher's memory of the framework
-- documents. Seeded with representative entries; intended to grow.
CREATE TABLE IF NOT EXISTS scope_sequence_references (
  id             SERIAL PRIMARY KEY,
  strand         TEXT NOT NULL,
  grade_level    TEXT NOT NULL,
  expected_skill TEXT NOT NULL, -- e.g. "Bar-model fluency for all 2-step word problems"
  source_document TEXT, -- e.g. "BleuLearn_Math_Assessment_Framework.docx"
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_scope_seq_strand_grade ON scope_sequence_references(strand, grade_level);

-- The AI-assisted, bias-aware second opinion. One row per assessment
-- submitted for review. The AI's analysis is evidence-only: it is never
-- given race, ethnicity, gender, or any demographic field (this platform
-- does not collect those fields at all -- see lib/aiReview.js), only the
-- documented evidence text the human assessor wrote, the relevant scope-
-- and-sequence reference, and the recommended action. Nothing in this
-- table is operative on its own -- track_assignments and accommodation
-- plans only change once a human explicitly approves via this record.
CREATE TABLE IF NOT EXISTS ai_assessment_reviews (
  id                     SERIAL PRIMARY KEY,
  target_type            TEXT NOT NULL CHECK (target_type IN ('placement_assessment','iep_evaluation','gifted_calibration_checkin','curriculum_gap_finding')),
  target_id              INTEGER NOT NULL,
  ai_analysis            TEXT NOT NULL,
  ai_agrees_with_human   BOOLEAN, -- NULL is a legitimate third state: AI was unavailable, no opinion given -- distinct from true/false (agrees/disagrees)
  bias_risk_flags        TEXT, -- documented, specific concerns (e.g. "evidence is impressionistic, not work-sample-based"); NULL if none found
  status                 TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review','approved','overridden')),
  human_decision_notes   TEXT, -- required when a teacher overrides the AI's read -- the documented reasoning, not a silent click
  reviewed_by            INTEGER REFERENCES users(id),
  reviewed_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ai_review_target ON ai_assessment_reviews(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_ai_review_status ON ai_assessment_reviews(status);

-- Same situation as users.role above: the real fix is in invite_codes'
-- CREATE TABLE statement, which now includes case_manager from the start.
-- This is a best-effort safety net only, for the same documented reason.
ALTER TABLE invite_codes DROP CONSTRAINT IF EXISTS invite_codes_role_check;
ALTER TABLE invite_codes ADD CONSTRAINT invite_codes_role_check_v2 CHECK (role IN ('teacher','admin','case_manager'));
